# Generated by Django 5.2.3 on 2025-06-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0004_course_duration_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Полное имя студента', max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(help_text='Контактный email студента', max_length=254, verbose_name='Email')),
                ('organization', models.CharField(blank=True, help_text='Учебное заведение или организация', max_length=255, null=True, verbose_name='Организация')),
                ('profile_photo', models.ImageField(blank=True, help_text='Загрузите фото профиля (рекомендуемый размер: 200x200px)', null=True, upload_to='student_photos/', verbose_name='Фото профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный профиль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи на курс')),
                ('status', models.CharField(choices=[('enrolled', 'Записан'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('suspended', 'Приостановлен'), ('dropped', 'Отчислен')], default='enrolled', max_length=20, verbose_name='Статус обучения')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Процент выполнения курса (0-100)', verbose_name='Прогресс (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения курса')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Оценка по курсу (например, 4.75)', max_digits=5, null=True, verbose_name='Итоговая оценка')),
                ('instructor_notes', models.TextField(blank=True, null=True, verbose_name='Комментарии преподавателя')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='skills.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='student.studentprofile', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
