# Generated by Django 5.2.1 on 2025-05-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название курса"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название навыка"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание навыка"
                    ),
                ),
                (
                    "is_base",
                    models.BooleanField(default=False, verbose_name="Базовый навык"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="skills",
                        to="skills.course",
                        verbose_name="Связанные курсы",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_skills",
                        to="skills.skill",
                        verbose_name="Предварительные навыки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["name"],
            },
        ),
    ]
