# Generated by Django 5.2.1 on 2025-05-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="Название на английском для отображения на графе",
                max_length=200,
                null=True,
                verbose_name="Английское название",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="Название на английском для отображения на графе",
                max_length=200,
                null=True,
                verbose_name="Английское название",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_skills",
                to="skills.skill",
                verbose_name="Необходимые навыки",
            ),
        ),
    ]
