# Generated by Django 5.2.1 on 2025-05-17 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_course_name_en_skill_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="name_en",
        ),
    ]
