# Generated by Django 5.2.3 on 2025-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_course_name_en_remove_skill_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (часы)'),
        ),
    ]
