# Generated by Django 5.2.3 on 2025-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0002_dqnrecommendation_dqntrainingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqnrecommendation',
            name='alternative_tasks_considered',
            field=models.JSONField(blank=True, help_text='Список других заданий по тому же навыку с их Q-values', null=True, verbose_name='Рассмотренные альтернативы'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='dependent_skills_snapshot',
            field=models.JSONField(blank=True, help_text='Список навыков, которые зависят от рекомендуемого, с их BKT вероятностями', null=True, verbose_name='Снимок зависимых навыков'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='llm_explanation',
            field=models.TextField(blank=True, help_text='Сгенерированное LLM объяснение рекомендации на естественном языке', verbose_name='LLM объяснение'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='llm_explanation_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время генерации LLM объяснения'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='prerequisite_skills_snapshot',
            field=models.JSONField(blank=True, help_text='Список prerequisite навыков с их BKT вероятностями на момент рекомендации', null=True, verbose_name='Снимок prerequisite навыков'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='student_progress_context',
            field=models.JSONField(blank=True, help_text='История попыток студента по данному навыку и связанным навыкам', null=True, verbose_name='Контекст прогресса студента'),
        ),
        migrations.AddField(
            model_name='dqnrecommendation',
            name='target_skill_info',
            field=models.JSONField(blank=True, help_text='Подробная информация о навыке, для которого рекомендуется задание', null=True, verbose_name='Информация о целевом навыке'),
        ),
        migrations.AddField(
            model_name='studentcurrentrecommendation',
            name='llm_explanation',
            field=models.TextField(blank=True, help_text='Объяснение рекомендации на естественном языке, сгенерированное LLM', verbose_name='LLM объяснение'),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='llm_explanation',
            field=models.TextField(blank=True, help_text='Объяснение рекомендации, которая привела к этой попытке, сгенерированное LLM', verbose_name='LLM объяснение'),
        ),
    ]
