# Generated by Django 5.2.3 on 2025-06-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0002_transfer_data_from_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('task_type', models.CharField(choices=[('single', 'Один вариант ответа'), ('multiple', 'Множественный выбор'), ('true_false', 'Верно/Неверно')], default='single', max_length=20, verbose_name='Тип задания')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('question_text', models.TextField(verbose_name='Формулировка задачи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Объяснение ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное задание')),
                ('courses', models.ManyToManyField(related_name='tasks', to='methodist.course', verbose_name='Связанные курсы')),
                ('skills', models.ManyToManyField(related_name='tasks', to='methodist.skill', verbose_name='Связанные навыки')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='methodist.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
    ]
