# Generated by Django 5.2.3 on 2025-06-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0003_task_taskanswer'),
    ]

    operations = [
    ]
