# Generated by Django 5.2.3 on 2025-06-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0004_auto_20250611_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='video_url',
        ),
    ]
