# Generated by Django 5.2.3 on 2025-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0005_remove_task_image_remove_task_video_url'),
        ('skills', '0003_remove_course_name_en_remove_skill_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='prerequisites',
        ),
        migrations.AlterField(
            model_name='task',
            name='courses',
            field=models.ManyToManyField(related_name='tasks', to='skills.course', verbose_name='Связанные курсы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(related_name='tasks', to='skills.skill', verbose_name='Связанные навыки'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
