# Generated by Django 5.2.3 on 2025-06-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_remove_skill_courses_remove_skill_prerequisites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='explanation',
        ),
    ]
